### ISSUE TITLE
能把网络仓库补上吗

### ISSUE THREAD

**Issue by MrXiaoM** [codethink-cn/xiaoming#3]
项目 pom 里没有可以访问的网络仓库，不想去找仓库或者手动补库，为了能让更多 Contributor 能省下补库的时间，建议让仓库能够开箱导入  IDE 即用

> 嗯… 无法访问此页面
> 检查 maven.chuanwise.cn 中是否存在拼写错误。
> 如果拼写正确，请尝试运行 Windows 网络诊断。
> DNS_PROBE_FINISHED_NXDOMAIN

另外，我找不到 WiseToolkit 及其开源地址，估计只能从 releases 中把 WiseTookit 分离出来了

**Comment by Chuanwise** [comment]
可以。项目正在重构并迁移到 `gradle`，正在整理和发布相关库，并配置好 `build.gradle`，避免补库。

**Comment by MrXiaoM** [comment]
done
